title: Yet Another Tech Blog
author: Matthieu Heimer
author: matt.heimer@gmail.com
description: Frequently infrequent thoughts on technology.
markdown: GFM
highlighter: pygments
theme: minima
repository: chasetec/chasetec.github.io
